apiVersion: v1
kind: Secret
metadata:
  name: registryapi-secret
  namespace: netcicdbook
type: Opaque
data:
  postgres-host: cG9zdGdyZXNxbC1zZXJ2aWNl # Base64 de "postgresql-service"
  postgres-port: NTQzMg== # Base64 de "5432"
  postgresql-user: YWRtaW4=  # Base64 de "admin"
  postgresql-password: YWRtaW4xMjM= # Base64 de "admin123"
  postgresql-db: cmVnaXN0cnlkYg== # Base64 de "registrydb"
  rabbitmq-host: YW1xcDovL3JhYmJpdG1xLWJ1cy1zZXJ2aWNl # Base64 de "amqp://rabbitmq-bus-service"
  rabbitmq-user: YWRtaW4=   # Base64 de "admin"
  rabbitmq-password: cGFzc3dvcmQ= # Base64 de 'password'
  
