apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: netcicdbook
spec:
  selector:
    app: ms-postgresql-registry-db  #Busca los pods con esta etiqueta para asociar el service
  ports:
  - port: 5432                      #Puerto externo que expone el servicio
    protocol: TCP                   #Protocolo usado TCP
    targetPort: 5432                #Puerto Interno del contenedor
  type: ClusterIP                   #Solo accesible dentro del clúster de K8