apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
  namespace: netcicdbook
data:
  init.js: |
    db = db.getSiblingDB('AuditoryDB');
    db.createUser(
        {
            user: process.env.MONGO_INITDB_ROOT_USERNAME,
            pwd: process.env.MONGO_INITDB_ROOT_PASSWORD,
            roles: [
                {
                    role: "readWrite",
                    db: "AuditoryDB"
                }
            ]
        }
    );
    db.createCollection('UserRecord');

