apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: netcicdbook
spec:
  selector:
    app: ms-mongo-auditory-db #Busca los pods con esta etiqueta para asociar el service
  ports:
  - port: 27017               #Puerto externo que expone el servicio
    protocol: TCP             #Protocolo usado TCP
    targetPort: 27017         #Puerto Interno del contenedor
  type: ClusterIP             #Solo accesible dentro del clúster de K8