apiVersion: v1
kind: Service
metadata:
  name: auditoryapi-service
  namespace: netcicdbook
spec:
  selector:
    app: ms-auditory-api    #Busca los pods con esta etiqueta para asociar el service
  ports:
  - name: http
    port: 5300              #Puerto externo que expone el servicio
    targetPort: 8080        #Puerto Interno del contenedor
  type: LoadBalancer        #Accesible desde fuera del cluster
  loadBalancerIP: 52.178.1.85