apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: netcicdbook
  labels:
    app: ms-rabbitmq-bus
type: Opaque
data:
  rabbitmq-user: YWRtaW4=   # Base64 de "admin"
  rabbitmq-password: cGFzc3dvcmQ= # Base64 encoded 'password'
  
