apiVersion: v1
kind: Service
metadata:
  name: worktime-app-service
  namespace: netcicdbook
spec:
  selector:
    app: worktime-app       #Busca los pods con esta etiqueta para asociar el service
  ports:
  - name: http
    port: 5100              #Puerto externo que expone el servicio
    targetPort: 80          #Puerto Interno del contenedor
  type: LoadBalancer        #Accesible desde fuera del cluster